sassafrastech/madeline

- Gemfile
- Gemfile.lock
- app/models/currency.rb
- app/models/division.rb
- app/models/organization.rb
- db/migrate/20151231160304_create_organizations.rb
- db/migrate/20151231160846_create_currencies.rb
- db/migrate/20151231161821_create_divisions.rb
- db/migrate/20151231162855_create_division_hierarchies.rb
- db/schema.rb
- spec/factories/currencies.rb
- spec/factories/divisions.rb
- spec/factories/organizations.rb
- spec/models/currency_spec.rb
- spec/models/division_spec.rb
- spec/models/organization_spec.rb
* creates organizations, currencies, and divisions
* updates factories where necessary
* updates models where necessary
* adds `closure_tree` gem to manage division hierarchies
> 3777: Creates models/tables needed for divisions

- Gemfile
- Gemfile.lock
- app/models/country.rb
- app/models/currency.rb
- app/models/division.rb
- app/models/language.rb
- app/models/legacy/division.rb
- app/models/legacy/loan.rb
- app/models/legacy/translation.rb
- app/models/loan.rb
- app/models/media.rb
- app/models/organization.rb
- app/models/organization_snapshot.rb
- app/models/person.rb
- app/models/translation.rb
- app/models/user.rb
- lib/tasks/auto_annotate_models.rake
- spec/factories/countries.rb
- spec/factories/currencies.rb
- spec/factories/divisions.rb
- spec/factories/languages.rb
- spec/factories/loans.rb
- spec/factories/media.rb
- spec/factories/organizations.rb
- spec/factories/people.rb
- spec/factories/translations.rb
- spec/factories/users.rb
Just an itsy-bitsy PR to add the model & factory annotations automatically. They'll update alongside running `db:migrate` with new schema changes.
> 3736: annotates models

- app/views/devise/passwords/edit.html.erb
Ensure devise branch is correctly merged.
> 3974: Devise

- app/assets/stylesheets/admin/loans/tabs.scss
- app/views/admin/loans/_tab.slim
- app/views/admin/loans/_tabs.slim
Fix bug related to tabs not displaying with gray background as expected when active.
> 4206 tab colors

- app/assets/javascripts/admin/timeline/select_all.coffee
- app/views/admin/loans/timeline/_project_step.html.slim
- app/views/admin/loans/timeline/_timeline.html.slim
- app/views/admin/loans/timeline/_timeline_header.slim
Refactor multi-select form
Refactor selecting multiple steps so that multi-select and batch actions will not interfere with other forms on the page.
> 3767 multiselect steps

- app/views/admin/loans/timeline/batch/_batch_actions.html.erb
- app/views/admin/project_steps/_show.html.slim
- config/locales/en/en.yml
Refine modal titles in project step and log
> 4513 modal titles

- app/views/layouts/admin/_site_menu.html.slim
- config/locales/en/en.yml
- Remove Reports from main menu
- Ensure menu items are translatable
> 4573 remove reports from menu

- app/views/admin/divisions/_divisions_grid.html.slim
- app/views/admin/loans/_loans_grid.html.slim
- app/views/admin/organizations/_organizations_grid.slim
- app/views/admin/people/_people_grid.slim
Remove eye filter icon from index tables
> 4570 filter icon

- app/views/admin/divisions/index.html.slim
> 4575: Add styles to divisions index table

- app/views/admin/divisions/index.html.slim
- app/views/admin/loans/index.html.slim
- app/views/admin/organizations/index.html.slim
- app/views/admin/people/index.html.slim
Move export to CSV below index table
> 4574 move export to csv button

- app/assets/stylesheets/admin/index_table.scss
- app/helpers/application_helper.rb
- app/views/admin/divisions/_divisions_grid.html.slim
- app/views/admin/divisions/index.html.slim
- app/views/admin/loans/_loans_grid.html.slim
- app/views/admin/loans/index.html.slim
- app/views/admin/organizations/_loans.html.slim
- app/views/admin/organizations/_organizations_grid.slim
- app/views/admin/organizations/index.html.slim
- app/views/admin/people/_people_grid.slim
- app/views/admin/people/index.html.slim
- config/locales/en/en.yml
Show message when filters return no records in grid
> 4578 bug loans index no records

- app/assets/stylesheets/admin/_index_table.scss
- app/helpers/application_helper.rb
- app/views/admin/common/_grid.slim
- app/views/admin/divisions/index.html.slim
- app/views/admin/loans/index.html.slim
- app/views/admin/organizations/index.html.slim
- app/views/admin/people/index.html.slim
- db/schema.rb
- Move export to CSV to grid partial
- Remove empty space around button due to hidden note
> 4574: Hide export to CSV when no records

- app/assets/stylesheets/admin/logs/_log_modal.scss
Ensure log modal text input and text area is appropriately sized
> 4606 bug fix text area

- app/assets/javascripts/backbone/views/project_step_view.coffee
Ensure calendar reloads when a step saved or changed
> 4625: Refresh calendar after calendar step saves

- app/assets/javascripts/backbone/views/calendar_view.js.coffee
- app/assets/stylesheets/admin/calendar/_calendar.scss
- app/assets/stylesheets/admin/logs/_logs.scss
- app/views/admin/calendar/index.html.slim
Allows steps to be viewed, edited, and deleted inside general calendar
> 4554: Enable opening of step modal from general calendar

- app/assets/javascripts/backbone/views/project_step_view.coffee
- app/controllers/admin/project_logs_controller.rb
- app/views/admin/project_logs/_step_logs.html.slim
- Remove add log button at bottom of logs list
- Ensure last deleted log returns view to no logs view
> 4605 bug fix double log button

- app/views/admin/loans/_loans_grid.html.slim
- app/views/admin/organizations/_organizations_grid.slim
- config/locales/en/en.yml
Add two missing columns into CSV export
> 4515 csv columns

- app/views/admin/loans/print.slim
- Ensure print memo fails gracefully when no criteria
> 3759: Show TOC only if loan criteria exists

- app/assets/stylesheets/admin/_tree.scss
- app/assets/stylesheets/admin/admin.scss
- A sass-rails bug is not loading in Sass variables as expected.
- This is a work around.
> 4825: Fix Sass error

- app/assets/javascripts/backbone/views/loan_charts_view.coffee
- app/views/admin/loans/content/_breakeven_charts.html.slim
- Address pull request changes from #129
> 4993 charts loan memo

- app/assets/javascripts/backbone/views/editable_table_view.js.coffee
- Adjustments to edit breakeven table requested in #133
> 5014 editable tables

- app/assets/javascripts/backbone/views/loan_charts_view.coffee
- app/assets/javascripts/backbone/views/loan_questionnaires_view.coffee
- app/assets/stylesheets/admin/loans/_charts.scss
- app/views/admin/loans/content/_breakeven_charts.html.slim
- app/views/admin/loans/content/_questionnaire_form.html.slim
- app/views/admin/loans/content/_questionnaire_group.html.slim
- app/views/layouts/base.html.slim
- Fix styling tweaks and bugs related to breakeven charts
> 5098 charts styling

- app/assets/stylesheets/admin/logs/_log_form.scss
Make log form select form elements the same size
> 5117: Make log form selects the same size

- app/assets/javascripts/backbone/views/move_step_modal_view.coffee
- app/views/admin/project_steps/_show.html.slim
Bug fixes related to #4836:
- Ensure completed date shows if a step has been completed
- When a completed date is changed, do not show log error message initially
- Show log error message only when there is no summary when log form submitted
> 4836 step dates

- app/assets/stylesheets/admin/_colors.scss
- app/assets/stylesheets/admin/loans/timeline/_table.scss
- app/views/admin/loans/timeline/table/_group.html.slim
- app/views/admin/loans/timeline/table/_step.html.slim
- Style step groups and spacers in timeline table
- Add cog icon to step groups as part of Redmine issue 5000
> 5158 styling of project groups in steps table

- app/models/legacy/member.rb
- app/models/legacy/project_event.rb
Steps are now visible on import, now that root project group is set.
> 5164 root project group

- app/models/breakeven_table_question.rb
- spec/models/breakeven_table_question_spec.rb
```ruby
{
'products': [
{ 'name': 'Product 1', 'description': 'Description', 'unit': 'Widgets', 'price': 100, 'cost': 50, 'quantity': 800 },
{ 'name': 'Product 2', 'description': 'Description', 'unit': 'Stamp books', 'price': 120, 'cost': 60, 'quantity': 300 },
{ 'name': 'Product 3', 'description': 'Description', 'unit': 'Flin Flons', 'price': 150, 'cost': 70, 'quantity': 100 },
],
'fixed_costs': [
{ 'name': 'Rent', 'amount': 1_5000 },
{ 'name': 'Worker owners', 'amount': 28_000.0 },
{ 'name': 'Employees', 'amount': 10_000.0 },
{ 'name': 'Sales', 'amount': 10_000 },
{ 'name': 'Utilities', 'amount': 2_000.0 },
{ 'name': 'Insurance', 'amount': 1_000.0 },
],
'periods': 4,
'units': 'Months',
}
```
```ruby
{
revenue: [
{ name: 'Product 1', quantity: 800.0, amount: 100.0, total: 80_000.0, …
```
> 5135 breakeven rampup

- app/assets/javascripts/backbone/views/timeline_select_steps_view.coffee
- app/assets/javascripts/backbone/views/timeline_table_view.coffee
- app/assets/javascripts/backbone/views/timeline_view.coffee
- app/assets/stylesheets/admin/loans/timeline/_table.scss
- app/views/admin/loans/timeline/_top_controls.slim
> 5143: Refactor TimelineSelectStepsView to work on table and list

- app/assets/javascripts/backbone/views/project_step_modal_view.coffee
- app/assets/javascripts/backbone/views/timeline_table_view.coffee
- app/controllers/admin/project_steps_controller.rb
- app/models/project_group.rb
- app/models/project_step.rb
- app/views/admin/loans/timeline/_main.html.slim
- app/views/admin/project_steps/_form.html.slim
- app/views/admin/project_steps/_modal_content.html.slim
- db/seeds.rb
- lib/tasks/fake_data.rake
- spec/factories/loans.rb
- spec/factories/project_groups.rb
- Add child step from group menu
> 5002 add child step from context menu

- app/assets/stylesheets/admin/loans/timeline/_table.scss
- app/models/project_step.rb
- app/views/admin/loans/timeline/_header.html.slim
- app/views/admin/loans/timeline/_step.html.slim
- config/locales/en/project_logs.en.yml
- Add log summaries to timeline table
> 5112 show log summaries

- app/assets/stylesheets/admin/loans/_tables.scss
- app/models/breakeven_table_question.rb
- app/views/admin/loans/questionnaires/_breakeven_rampup_row.html.slim
- app/views/admin/loans/questionnaires/_breakeven_table_question.html.slim
- config/locales/en/loans.en.yml
- spec/models/breakeven_table_question_spec.rb
Made some changes to the styles
> 5134 period fields

- app/helpers/application_helper.rb
- app/helpers/old_system_helper.rb
- app/views/admin/loans/_details.html.slim
- config/locales/en/en.yml
It is hard to read the url in the url bar, so here is it decoded in Chrome.
> 5300: Add initial transaction menu

- app/assets/stylesheets/admin/loans/_rampup_table.scss
- app/views/admin/loans/questionnaires/breakeven_rampup/_rampup_table.html.slim
> 5362: Adjust spacing between Revenue and COGS on rampup table

- app/assets/javascripts/backbone/views/project_step_modal_view.coffee
- app/assets/javascripts/backbone/views/timeline_table_view.coffee
- app/controllers/admin/loan_questions_controller.rb
- app/controllers/admin/project_steps_controller.rb
- app/models/project_step.rb
- app/models/timeline_entry.rb
- app/views/admin/project_steps/_modal_content.html.slim
- config/locales/en/en.yml
- spec/models/project_step_spec.rb
- Add ability to have a preceding step (backend and frontend)
- Hide scheduled start date if preceding step is present in step form
- Scheduled start date depending on preceding step shows in timeline
> 5092 add dependent step

- app/assets/javascripts/backbone/views/loan_questions_view.coffee
- app/assets/stylesheets/admin/loan_questions/_loan_questions.scss
- app/serializers/loan_question_serializer.rb
- Show loan types that are required per question in questionnaire index
> 5441 display required loan types

- app/views/admin/project_logs/_form.html.slim
- config/locales/en/en.yml
- Display step inside project log modal
> 5452 display step summary

- app/views/admin/loans/_loans_grid.html.slim
- app/views/admin/loans/index.html.slim
- config/locales/en/loans.en.yml
* Take out "Created" and put in "Point Person"
* Add "Target End Date" column AND filter
> 5451: Updated loan index table

- app/assets/javascripts/backbone/views/timeline_table_view.coffee
- app/assets/stylesheets/admin/_colors.scss
- app/assets/stylesheets/admin/loans/timeline/_table.scss
- app/views/admin/loans/timeline/_step.html.slim
- Show relationships between steps when hovering over step
- Highlight start and end date of active step
- Highlight start date of any dependent steps, if existing
- Highlight completed date of precedent step, if it exists
> 4999 show linked steps on mouseover

- app/assets/javascripts/backbone/views/timeline_table_view.coffee
- Do not highlight a step with no related steps
> 4999: Only show relationships if there are related steps

- app/assets/javascripts/backbone/views/log_modal_view.coffee
- app/assets/javascripts/backbone/views/move_step_modal_view.coffee
- app/views/admin/project_logs/_form.html.slim
- Do not show empty log alert on first load of change step date log modal
- Only show empty log alert when user saves
> 5553 bug fix alert on change date of step

- app/assets/javascripts/backbone/views/calendar_view.js.coffee
- app/assets/stylesheets/admin/calendar/_calendar.scss
- app/controllers/admin/timeline_step_moves_controller.rb
- app/models/calendar_event.rb
- app/serializers/calendar_event_serializer.rb
- app/views/admin/calendar/_event.html.slim
- app/views/admin/calendar/_legend.html.slim
- config/locales/en/en.yml
- config/routes.rb
- Ensure steps that are not finalized can be moved
- Ensure changing a step date with dependents also moves the dependents
- Ensure steps with precedent steps cannot be moved
- Indicate steps with precedent steps on the calendar
> 5116 bugfix date change on unfinalized steps

- app/models/loan_response.rb
- app/views/admin/loans/questionnaires/_questionnaire_group.html.slim
- Bug fix: Add text input for loan response strings
> 5587: Add string/short answer option for loan responses

- app/assets/javascripts/backbone/views/loan_questions_view.coffee
- app/assets/stylesheets/admin/loan_questions/_form.scss
- app/assets/stylesheets/admin/loan_questions/_loan_questions.scss
- app/assets/stylesheets/admin/loans/_questionnaires.scss
- app/controllers/admin/loan_questions_controller.rb
- app/serializers/loan_question_serializer.rb
- app/views/admin/loan_questions/_form.html.slim
- app/views/admin/loans/questionnaires/_questionnaire_group.html.slim
- config/locales/en/loan_questions.en.yml
- Add active/inactive checkbox in loan question form
- Adjust styling of inactive questions in manage loan questions
- Adjust styling of inactive questions inside loan questionnaire
In the develop branch, inactive questions and groups were already are hidden by default if they did not have a response.
> 5074 inactive status loan questions

- app/views/admin/loans/_form.html.slim
- app/views/admin/loans/show.html.slim
- config/locales/en/en.yml
I think this should match what was requested in the ticket. Here are some screens.
> 5635: Adding loan id to loan pages

- app/views/admin/basic_projects/_basic_projects_grid_definition.html.slim
- app/views/admin/basic_projects/index.html.slim
- app/views/admin/loans/_loans_grid_definition.html.slim
- app/views/admin/loans/index.html.slim
- app/views/layouts/admin/_site_menu.html.slim
- config/locales/en/basic_projects.en.yml
- config/locales/en/en.yml
- config/locales/en/loans.en.yml
- Move project menu item lower in main menu
- Convert basic projects and loans to use "Agent" for filter
- Adjust YAML for agent and agents in basic projects and loans
> 5592 project index styling tweaks

- app/assets/javascripts/backbone/views/expander.coffee
- app/assets/stylesheets/_expander.scss
- app/assets/stylesheets/application.scss
- app/views/admin/project_logs/_log_list.html.slim
- app/views/admin/project_steps/_modal_content.html.slim
- Move show/hide logs list links into logs list partial
- Ensure show/hide logs links are on same line as expand/condense logs links
- Ensure refactor works across app where logs lists are displayed
- Hide expand all link when logs list is not expanded
> 5674 styling display logs

- app/controllers/admin/basic_projects_controller.rb
- app/views/admin/basic_projects/_form.html.slim
- app/views/admin/basic_projects/index.html.slim
- app/views/admin/basic_projects/new.html.slim
- config/locales/en/basic_projects.en.yml
- config/locales/en/en.yml
- Add button on projects index to new project page
- Add form to new project page
- Allow new project to be saved
- Add division to project form
> 5594 new project

- app/assets/stylesheets/admin/loans/timeline/_table.scss
> 5880: Fix missing separation between project groups

- app/controllers/admin/basic_projects_controller.rb
- app/controllers/admin/divisions_controller.rb
- app/controllers/admin/loans_controller.rb
- app/controllers/admin/organizations_controller.rb
- app/controllers/admin/people_controller.rb
- Bug fix: Ensure CSV tables export from index grids
> 5876 export tables to csv

- app/assets/stylesheets/admin/admin.scss
- app/assets/stylesheets/admin/dashboard/_dashboard.scss
- app/controllers/admin/dashboard_controller.rb
- app/policies/application_policy.rb
- app/policies/dashboard_policy.rb
- app/views/admin/dashboard/dashboard.html.slim
- app/views/layouts/admin/_site_menu.html.slim
- config/routes.rb
- Create dashboard page
- Create link in menu
> 5911 create dashboard page

- app/assets/javascripts/backbone/views/calendar_view.coffee
- app/views/admin/calendar/_event.html.slim
- Fix bug when moving project start and end date in dashboard and main calendar
> 5981 bug fix change project start end date in calendar

- app/assets/stylesheets/admin/calendar/_calendar.scss
- Remove yellow background on current day
- Applies to all calendars
> 5990: Remove background from current day

- app/assets/stylesheets/admin/_general.scss
- app/assets/stylesheets/admin/_index_table.scss
- app/assets/stylesheets/admin/dashboard/_dashboard.scss
- app/helpers/application_helper.rb
- app/helpers/grid_helper.rb
- app/views/admin/basic_projects/_basic_projects_grid_definition.html.slim
- app/views/admin/basic_projects/index.html.slim
- app/views/admin/common/_grid.html.slim
- app/views/admin/dashboard/_recent_projects_grid_definition.html.slim
- app/views/admin/dashboard/dashboard.html.slim
- app/views/admin/divisions/_divisions_grid_definition.html.slim
- app/views/admin/divisions/index.html.slim
- app/views/admin/loans/_loans_grid_definition.html.slim
- app/views/admin/loans/index.html.slim
- app/views/admin/organizations/_organizations_grid_definition.html.slim
- app/views/admin/organizations/index.html.slim
- app/views/admin/people/_people_grid_definition.html.slim
- app/views/admin/people/index.html.slim
- app/views/admin/project_logs/_log_list.html.slim
- config/locales/en/en.yml
> 6020 only display one "no record" message for tables

- app/assets/stylesheets/admin/forms/_forms.scss
- app/views/admin/project_logs/_fields.html.slim
- Add class for read-only form elements
- Ensure elements are aligned with their labels
> 5935: Ensure step name is aligned with label in log form

- app/assets/stylesheets/admin/dashboard/_dashboard.scss
- app/views/admin/dashboard/dashboard.html.slim
- Make logs padding consistent with remainder of site
- Make headers of sections consistent in dashboard
> 6037 tweaks to dashboard log list

- app/models/timeline/step_duplication.rb
- config/locales/en/en.yml
- spec/models/timeline/step_duplication_spec.rb
resolve "that day doesn't exist in that month" issue use last day of month instead
> 6096 errors on duplicate step

- app/controllers/concerns/transaction_listable.rb
- app/views/admin/accounting/transactions/_transactions_grid_definition.html.slim
- app/views/admin/accounting/transactions/index.html.slim
- app/views/admin/common/_grid.html.slim
- app/views/admin/loans/_transactions.html.slim
- Add CSV export for transactions
> 5833 csv export transactions

- app/assets/stylesheets/admin/loans/timeline/_table.scss
- app/helpers/project_step_helper.rb
- app/models/project_step.rb
- app/views/admin/timeline/_step.html.slim
- config/locales/en/en.yml
- Remove gray background on steps
- Show completed message with checkbox in step status
- Show completed days late message in step status, if applicable
> 5884 style changes timeline completed steps

- app/controllers/admin/basic_projects_controller.rb
- app/controllers/admin/divisions_controller.rb
- app/controllers/admin/loans_controller.rb
- app/controllers/admin/organizations_controller.rb
- app/controllers/admin/people_controller.rb
- app/views/admin/basic_projects/_basic_projects_grid_definition.html.slim
- app/views/admin/divisions/_divisions_grid_definition.html.slim
- app/views/admin/loans/_loans_grid_definition.html.slim
- app/views/admin/organizations/_organizations_grid_definition.html.slim
- app/views/admin/people/_people_grid_definition.html.slim
Fix CSV export in basic projects, divisions, loans, organizations, and people grids
> 6146 bug fix csv export

- app/assets/stylesheets/admin/_general.scss
- app/assets/stylesheets/admin/_index_table.scss
- Move CSV export button closer to table
> 6197 tweaks to csv export

- app/controllers/admin/basic_projects_controller.rb
- app/controllers/admin/loans_controller.rb
- Ensure locale is passed to projects calendars
- Ensure projects calendars translate to Spanish
> 6149 add missing translations

- app/assets/stylesheets/admin/dashboard/_dashboard.scss
- app/views/admin/dashboard/dashboard.html.slim
- Adjust heading margins and padding in sections in dashboard
> 6196 tweak dashboard headers

- app/views/admin/project_logs/index.html.slim
- Ensures media can be added to a log from logs list page
> 6155: Add media modal to log list page

- app/controllers/admin/project_groups_controller.rb
- app/models/project_group.rb
- app/views/admin/project_groups/_modal_content.html.slim
- spec/models/project_group_spec.rb
- Allow parent group to be changed on existing group or new group
- Add specs to test parent group changes
> 6133 child groups

- app/views/admin/loans/_form.html.slim
- Include blank choice for organization choice in loan form
> 6159: Include blank choice for organization in loan form

- app/assets/stylesheets/admin/loans/_charts.scss
- Fix overlapping pie charts on smaller screens
> 6207: On smaller screens, make pie charts be full-width

- config/routes.rb
- Load dashboard page when logging in instead of recent loans
> 6116: On login, load dashboard page instead of recent loans

- app/models/accounting/quickbooks/transaction_creator.rb
- spec/models/accounting/quickbooks/transaction_creator_spec.rb
This just adds a class that can add a loan disbursement to quickbooks. Will be used later on with other tickets.
> 6189 Add Transaction Creator class

- app/assets/javascripts/backbone/views/loan_charts_view.coffee
- app/assets/javascripts/backbone/views/loan_questionnaires_view.coffee
- app/views/admin/loans/questionnaires/_breakeven_charts.html.slim
- Fix numbers in pie charts
- When tree is loaded and expanded, pie chart displays as expected
- On window resize, resize charts
- If a breakeven question is expanded initially before user interaction, display the pie charts
> 6002 bugfix pie charts

- app/models/person.rb
- Show media for a person in person details page
> 6198: Display existing media for person

- app/views/admin/project_logs/_log_list.html.slim
- app/views/admin/project_steps/_modal_content.html.slim
Inside calendar step modal:
- Do not show "Show Logs" if there are no logs to display
- If there are logs, show the logs count in "Show/Hide Logs"
> 5791 tweaks show logs link

- app/assets/javascripts/backbone/views/timeline_table_view.coffee
- app/views/admin/timeline/_step.html.slim
- Show precedent's group in new dependent step's modal
> 6250 show group in new dependent step

- app/models/accounting/quickbooks/customer.rb
- app/models/accounting/quickbooks/transaction_creator.rb
- app/models/division.rb
- app/models/organization.rb
- db/migrate/20170511054647_add_qb_id_to_organization.rb
- db/schema.rb
- spec/models/accounting/quickbooks/customer_spec.rb
- spec/models/accounting/quickbooks/transaction_creator_spec.rb
This is a continuation of #317 use this link to see the differences from that PR. https://github.com/sassafrastech/madeline/compare/6280_add_disbursment_date...6281_create_customer_for_transaction
> 6281 create customer for transaction

- Gemfile
- Gemfile.lock
- app/models/loan_response_set.rb
- db/migrate/20170526012142_set_default_lock_version.rb
- db/schema.rb
- spec/features/admin/questionnaire_spec.rb
I feel like @hooverlunch might want to quickly review this when he gets back, but we can go ahead and merge it anyway.
> 6515 overwriting bug

- app/assets/javascripts/backbone/views/timeline_batch_actions_view.coffee
- spec/factories/project_steps.rb
- spec/features/admin/timeline_batch_actions_spec.rb
- Tests for adjust dates batch action
> 6434 batch adjust dates tests

- Gemfile
- Gemfile.lock
- config/initializers/session_store.rb
- db/migrate/20170705133455_add_sessions_table.rb
- db/schema.rb
> 6776 use active_record_store to store cookies

- app/views/admin/loans/questionnaires/_questionnaire_group.html.slim
Remove parent headings from each question heading
> 6501: Remove parents from question headings

- .env.example
there is no real code change needed.
most of the changes will happen on the production and staging servers.
I also left a note on https://redmine.sassafras.coop/issues/6193
> 6193 change env vars to mock data

- app/models/accounting/account.rb
- Allow accounts to be removed when resetting QuickBooks settings
> Fix accounting bug

- app/controllers/admin/loan_questions_controller.rb
- app/models/division.rb
- app/models/loan_question.rb
- app/models/loan_question_set.rb
- app/views/admin/loan_questions/_form.html.slim
- config/locales/en/loan_questions.en.yml
- db/migrate/20170816142318_add_division_to_question.rb
- db/migrate/20170816144924_change_division_on_questions.rb
- db/migrate/20170816150506_change_division_id_in_loan_question.rb
- db/migrate/20170816171303_remove_division_id_from_loan_question_sets.rb
- db/schema.rb
- spec/factories/loan_question_sets.rb
- spec/factories/loan_questions.rb
- spec/features/admin/questionnaire_spec.rb
- spec/models/loan_question_requirement_spec.rb
- spec/models/loan_question_set_spec.rb
- spec/models/loan_question_spec.rb
- spec/models/loan_response_set_spec.rb
- Remove division from question set model
- Add division to question model
- Ensure user can specify a division for each question
- Set root division to division for all existing questions
- Fix tests
> 6940 add division to questions

- app/models/loan_response.rb
- Earlier change created a bug: commit 9f37110fa8fcf56e379fd06449e4c5eabffa7253
> 7126 (6531): Restore original method

- app/models/loan_response.rb
- spec/factories/divisions.rb
- spec/factories/loan_questions.rb
- spec/models/loan_response_spec.rb
this has to be merged into https://github.com/sassafrastech/madeline/pull/382 on approval
> 7166 loan memo bug

- app/assets/stylesheets/admin/calendar/_calendar.scss
- Make step and loan events have same font-size in calendar
- Truncate loan names in calendar
> 6849 calendar events font size

- app/assets/stylesheets/admin/_general.scss
- app/assets/stylesheets/admin/_variables.scss
- app/assets/stylesheets/admin/calendar/_calendar.scss
- app/views/admin/calendar/_event.html.slim
- Make steps in calendar take one line instead of 2
- Refine icons in step events
> 6851 adjust step events design

- app/assets/stylesheets/admin/dashboard/_dashboard.scss
Add visual distinction between dashboard table header and rows
> 6927 table headings

- app/controllers/admin/loan_questions_controller.rb
- app/controllers/admin/loan_response_sets_controller.rb
- app/controllers/admin/loans_controller.rb
- app/controllers/concerns/questionnaire_renderable.rb
- app/models/filtered_question.rb
- app/models/loan_question.rb
- app/models/loan_response_set.rb
- app/policies/loan_question_policy.rb
- app/views/admin/loans/_form.html.slim
- spec/features/admin/questionnaire_spec.rb
- spec/features/admin/timeline_batch_actions_spec.rb
- spec/models/filtered_question_spec.rb
- spec/models/loan_filtered_question_spec.rb
- spec/policies/loan_question_policy_spec.rb
- spec/support/helpers/question_spec_helpers.rb
WIP - need to fix failing specs
> 7182 update question policy

- app/views/admin/project_logs/_log_list.html.slim
- Fix bug on last page of logs list
> 7147: Fix last page of logs list

- app/assets/stylesheets/admin/loans/timeline/_table.scss
- app/views/admin/timeline/_step.html.slim
- Show link icons to represent step dependency in timeline
> 4834 link icons date dependency

- app/views/admin/accounting/transactions/index.html.slim
- app/views/layouts/admin/_site_menu.html.slim
- spec/features/admin/accounting/transaction_flow_spec.rb
- Remove global transactions page
> 7448: Remove global transaction page

- app/assets/javascripts/backbone/views/timeline_table_view.coffee
- app/assets/stylesheets/admin/loans/_tabs.scss
- app/assets/stylesheets/admin/loans/timeline/_table.scss
- Ensure timeline table has a gray background
- Ensure timeline dropdown and dropup menus fully display
> 7354 wide timeline table

- app/assets/javascripts/backbone/views/timeline_table_view.coffee
- app/views/admin/project_steps/_modal_content.html.slim
- app/views/admin/timeline/_table.html.slim
Do we keep the delete option in the project step modal? @emitche 
I also left you some messages on Slack
> 7816 make calendar and timeline show 'show' modal by default

- Capfile
- Gemfile
- Gemfile.lock
- config/deploy.rb
- config/schedule.rb
- db/schema.rb
- db/seeds.rb
this was branched off #488 so it needs to be merged into that branch first before #488 is merged into develop
> 8100 update seeds

- app/assets/javascripts/admin/timeline_table_view.coffee
> 8056 prevent view-logs disabled link from working

- app/assets/javascripts/admin/timeline_table_view.coffee
> 8142 fix toggle

- app/assets/javascripts/admin/timeline_table_view.coffee
- app/assets/stylesheets/admin/loans/timeline/_table.scss
- app/views/admin/timeline/_step.html.slim
@emitche
I tried the clicks in an incognito browser and everything was fine. On the regular browser, for some reason it'd render `font` html tag inconsistently. This seems to be what is causing the breakage
I'll await your testing but this PR might just be closed
> 8025 add class

- app/models/legacy/loan_question.rb
- app/models/legacy/loan_response.rb
- app/models/legacy/loan_response_set.rb
- Adjust legacy models to use naming of older database in places that call data from the legacy table
> 8227: Ensure question renaming works with legacy data

- app/views/admin/loans/questionnaires/_questionnaire_group.html.slim
this fixes the bug of line breaks when editing in summernote
it should be merged into #530 before #530 is merges into master
> 8528 fix bug

- app/controllers/admin/organizations_controller.rb
- app/models/organization.rb
- app/views/admin/organizations/_form.html.slim
- db/migrate/20180621175058_update_country_for_coops.rb
- db/schema.rb
- spec/features/admin/organization_flow_spec.rb
With this, coops that have divisions that don't have currencies will have to be set manually
> 8554 make country required in coops

- app/controllers/admin/divisions_controller.rb
- app/helpers/application_helper.rb
- app/models/loan.rb
- app/views/public/loans/index.html.slim
- spec/features/loan_index_spec.rb
I branched off #547 so it has to be merged into it first before #547 goes into develop
> 8613 add link to public loan card

- app/assets/stylesheets/admin/_menu.scss
- app/views/layouts/admin/_user_div_info.html.slim
- Fix UI bug where header items jump when the division selector shows
> 8577 main header divisions bug

- app/models/division.rb
- app/models/loan.rb
- app/views/admin/divisions/_form.html.slim
- config/locales/en/en.yml
- spec/features/admin/division_flow_spec.rb
this needs to be merged into #554
> 8621 add nested divisions to division form

- app/controllers/admin/documentations_controller.rb
- app/policies/documentation_policy.rb
- app/views/admin/documentations/_form.html.slim
- app/views/admin/documentations/edit.html.slim
- config/locales/en/documentations.en.yml
- config/routes.rb
- spec/features/admin/documentation_spec.rb
The action buttons for the form look meh. I'm not sure what is causing it. Didn't want to take up more time looking into something I'm not sure of but the functionality works as it should
> 8779 edit documentation

- app/controllers/admin/project_steps_controller.rb
- app/views/admin/project_steps/_modal_content.html.slim
- config/locales/en/en.yml
- spec/models/project_step_spec.rb
I left a message on https://redmine.sassafras.coop/issues/7680
> 7680 assign members to timeline items

- app/assets/javascripts/admin/application_view.coffee
- app/helpers/admin_helper.rb
- Fix popovers.
- Popovers were not able to be opened and closed more than once. This bug fix resolves the issue.
> 8835 bugfix popovers

- app/assets/javascripts/summernote-init.js
- app/models/question.rb
- app/views/admin/loans/questionnaires/_questionnaire_group.html.slim
- app/views/admin/questions/_form.html.slim
> 8808 add summernote to explanation fields on question

- app/assets/stylesheets/admin/forms/_forms.scss
- app/views/admin/divisions/_form.html.slim
- Add documentation popovers to division form
> 8833: Add documentation popovers to division form

- spec/features/admin/documentation_spec.rb
I have added specs to cover the scenarios mentioned and also did a manual test. I was not able to recreate this bug.
> 8845 add specs to cover bugged area

- spec/models/accounting/quickbooks/data_extractor_spec.rb
This may not be the fix but I found a duplication
> 8838 remove duplicate before block method

- app/models/accounting/quickbooks/data_extractor.rb
- app/models/accounting/quickbooks/transaction_extractor.rb
- app/models/accounting/quickbooks/updater.rb
- spec/models/accounting/quickbooks/data_extractor_spec.rb
- spec/models/accounting/quickbooks/transaction_extractor_spec.rb
The fact that this took me so little time makes me worried that I've done something horribly wrong, but I've looked over the description many times and I think it's done. Let me know if I've missed something huge.
> 8701 refactor data extractor

- app/assets/stylesheets/admin/loans/_print.scss
- app/helpers/media_helper.rb
- app/views/admin/loans/print.html.slim
- Fix broken print loan memo
- Adjust how images display inside print loan memo
> 9118 bug fix print loan memo

- app/assets/stylesheets/admin/media/_media.scss
- app/views/admin/media/_modal_content.html.slim
- config/locales/en/en.yml
- Styling tweaks to media modal
- Language adjustments to media messages
> 9117 media modal styling tweaks

- app/controllers/application_controller.rb
- config/locales/en/loans.en.yml
- public/robots.txt
- Reduce error messages from bots (Redmine 9028)
- Address Pundit Not Authorized errors on the public namespace by showing an error page and error message (Redmine 8688)
> 9028 reduce error messages
