- app/controllers/application_controller.rb
- app/controllers/concerns/wordpress_embeddable.rb
- app/controllers/loans_controller.rb
- app/controllers/static_pages_controller.rb
- config/environments/development.rb
- config/environments/production.rb
- config/environments/test.rb
- config/routes.rb
- lib/wordpress_template.rb
- spec/fixtures/wordpress-rails.html
* Adds sample wordpress layout file for specs
* Refactors wordpress library logic to read from fixture in dev/test
* Namespaces wordpress-related routing logic
* Gives relative paths in environment configs for template fetch
* Factors wordpress update logic into `WordpressEmbeddable` concern
* Creates static pages controller for WP test page
> 3998: Wordpress Template Fixes

- .gitignore
- app/controllers/admin/project_steps_controller.rb
- app/models/project_step.rb
- app/policies/project_step_policy.rb
- app/views/admin/project_steps/_project_step.html.slim
- app/views/admin/project_steps/_shift_subsequent_confirm_modal.html.slim
- config/locales/en/en.yml
- config/routes.rb
modal confirmation and logic to shift out subsequent step schedule dates when prior step updated as late
> 4437 - shift subsequent project steps

- app/assets/javascripts/backbone/views/calendar_view.js.coffee
Fixes loading indicator showing when global calendar's empty dates are clicked
> 4609: Empty date click opens new step on loan calendar only

- app/models/calendar_event.rb
Fix a bug that did not show correct icon for a ghost step based on original project step's step type
> 4622: Add step type to ghost steps

- app/assets/javascripts/backbone/views/project_step_view.coffee
- app/views/admin/project_steps/_project_step.html.slim
- app/views/admin/project_steps/_shift_subsequent_confirm_modal.html.slim
Fix shift dates modal displaying when delete and duplicate step modals are displayed
- Move JS for shift dates into step view model
- Change class that opened modal when wrong action called
> 4518: Fix shift dates modal being opened during wrong actions

- app/assets/stylesheets/admin/_general.scss
- app/assets/stylesheets/embedded/_scaffolds.scss
- Is a work-around for a Sass inside Rails bug
Developer see the colors working properly unless branches are
changed or server is restarted. When that happens, the color
variables cannot be found without explicitly stating location.
> Explicitly give location of color variables

- app/assets/stylesheets/admin/loans/_tables.scss
- app/views/admin/loans/content/_breakeven_table_question.html.slim
Make columns wider in breakeven data tables.
Set minimum width so table does not scrunch
on small screens.
> 5111: Adjust size of columns

- app/views/admin/project_logs/_form.html.slim
Alert should show when there is no summary and user tries to save.
> 5425: Ensure log alert when no summary is present shows

- app/assets/stylesheets/admin/_date_picker.scss
- app/assets/stylesheets/admin/admin.scss
Fixes date picker being cut off underneath topmost header
> 4785: Condense content inside date picker

- app/views/admin/loans/timeline/_group.html.slim
- app/views/admin/loans/timeline/_step.html.slim
- Adjust step context menu to show menu above toggle
- Adjust group context menu to show opened menu above toggle
- Address menus that were cut off at the bottom of the page
> 5610 bugfix step context menu

- app/views/admin/dashboard/dashboard.html.slim
- Hide "Manage Logs" link when there are no logs in dashboard
> 6128: Hide Manage Logs link when no logs exist in dashboard

- app/assets/javascripts/backbone/views/loan_questionnaires_view.coffee
- Allows nodes to remain open on page reload
- When questionnaire is saved, open nodes are remembered
> 6018: Save the state of the questionnaire tree

- app/assets/stylesheets/admin/media/_media.scss
- app/helpers/admin_helper.rb
- app/helpers/media_helper.rb
- app/models/media.rb
- app/views/admin/media/_index.html.slim
- app/views/admin/media/_media_item.html.slim
- app/views/admin/project_logs/index.html.slim
- config/locales/en/en.yml
- Rearrange what is displayed for media information
- Display content type on media item
- Add icons to non-image files
- On hover of shortened filename, show full filename
- If no media items present in a section, do not display the section
> 6017 display media type on media attachment

- app/controllers/admin/project_steps_controller.rb
- app/models/project_group.rb
- app/models/project_step.rb
- app/models/timeline_entry.rb
- db/migrate/20170419144544_add_not_null_constraint_to_project_step_value.rb
- db/schema.rb
- On batch finalize of steps, use update method without validation
- Fix bug where batch finalize does not work for steps without step type
- Make step type value not be null or empty
- Set project groups to have a step type value
- Set project steps to have a step type value
> 6191 bug error on batch finalize steps

- app/assets/stylesheets/admin/media/_media.scss
- app/models/project_log.rb
- app/views/admin/media/_index.html.slim
- app/views/admin/project_logs/_log_list.html.slim
- Show media in show log
- Inside log list, display media
- Display media inside the expand/hide section of the log
- UI changes to media including displaying items inline with each other
> 6234 media in show log

- app/views/admin/project_logs/modal.html.slim
- Add attribute for modal background to not close the modal
- Ensures data is not lost from the log modal when editing
> 6219: Do not close the log modal when clicking outside it

- app/assets/javascripts/backbone/views/calendar_view.coffee
- app/assets/stylesheets/admin/calendar/_calendar.scss
- app/models/calendar_event.rb
- app/models/project_step.rb
- app/serializers/calendar_event_serializer.rb
- app/views/admin/calendar/_event.html.slim
- app/views/admin/calendar/_legend.html.slim
- Convert steps in calendars to span across dates
- Bug fixes related to displayed start and end dates
- Use underlying fullCalendar structure for step events to utilize pre-built classes
> 6394 display steps as spans in calendar

- app/controllers/admin/project_steps_controller.rb
- Fix bug that showed a no logs message in edit step modal when logs present
> 6393: Show logs inside timeline edit step modal

- app/assets/stylesheets/admin/loans/_questionnaires.scss
- app/views/admin/loans/questionnaires/_questionnaire_group.html.slim
- Temporarily remove page breaks from loan memo
- Temporarily remove headings for page breaks in loan memo
- Keep page breaks on breakeven table and charts
- Fix bug where page breaks were inconsistently being applied in loan memo
- An update for how page breaks appear in loan memo is slated for the next sprint
> 6574: Tempoarily remove page breaks from loan memo

- app/models/accounting/account.rb
- app/models/accounting/line_item.rb
- app/models/accounting/transaction.rb
- db/migrate/20170807122855_create_line_items.rb
- db/schema.rb
- spec/factories/accounting_line_items.rb
- spec/models/accounting/line_item_spec.rb
In the transaction model, I noticed there were two line items; one for credit and the other for debit. That being said, I'm not sure what the association is from transactions and accounts (i.e. has_many or has_one)
@hooverlunch
> 6905 add line item model with corresponding spec

- app/controllers/admin/project_steps_controller.rb
- app/controllers/admin/projects_controller.rb
- app/views/admin/project_steps/_modal_content.html.slim
- Show project name in the show view of the project step modal
- Ensures general calendar and dashboard calendar step events have project context
The show view of the project step modal appears in all calendars, but is not displayed in the timeline.
> 7134: Show project name in show view of modal

- config/deploy.rb
Fixes a bug where one developer was unable to deploy.
The initial pull request was here. https://github.com/sassafrastech/madeline/pull/469
> 7998: Add alternative url for deploying

- app/controllers/admin/accounting/transactions_controller.rb
- app/models/accounting/interest_calculator.rb
- app/models/accounting/transaction.rb
- db/migrate/20180222124353_add_locked_to_transactions.rb
- db/migrate/20180306112918_remove_lock_add_managed.rb
- db/schema.rb
- spec/factories/accounting_transactions.rb
- spec/models/accounting/interest_calculator_spec.rb
- spec/models/accounting/transaction_spec.rb
I stopped at the point where it says line_items should remain the same in the story. Skipping managed transactions will prevent the line items from being created all together.
Does this mean moving the condition to after the line items are created?
> 8003 skip locked txns

- config/initializers/wice_grid_config.rb
This should fix our CSV export issues. The encoding was selected for excel compatibility, but in theory the issue this config setting is trying to fix should really only impact older versions of excel, and TWW is mostly using google sheets anyway. We can obviously change this back at some point if needed, but unless TWW reports problems to us, I expect this is the best solution to these issues.
> 8760: Fixes CSV Exports

- app/views/admin/documentations/_form.html.slim
I disabled the HTML Identifier field and hid the calling action and calling controller fields
I did this so the user is able to differentiate between different documentations
When testing, it felt awkward that all the forms just had text areas saying to fill in page title, page content and summary content
> disable and hide fields
